gems:
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - "/vendor/"

# Настройки сайта
title: ГСАУ «ЧЛЦ»
subtitle: Государственное автономное учреждение «Чеченский лесопожарный центр»
email: rgu-2011@mail.ru
name: ГСАУ «Чеченский лесопожарный центр»
description: >
  Государственное автономное учреждение «Чеченский лесопожарный центр»

url: "http://lpc-chr.ru"
cover: "/assets/header_image.jpg"
logo: "/assets/logo.png"

# Build
markdown: kramdown
paginate: 3
paginate_path: "/page:num/"
inter_post_navigation: false
highlightjs_theme: "monokai_sublime"

# Настройки архивирования (см. https://github.com/jekyll/jekyll-archives/)
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: 'archive'
  permalinks:
    category: '/category/:name/'
    tag: '/tag/:name/'
    
    
social:
    - name: Skype
      icon: skype
      username: chphs0951
      url: skype:chphs0951?call
      desc: Позвонить в Skype
      share: false
    
    - name: Городской телефон
      icon: tty
      username: 22-48-94
      url: tel:88712294894
      desc: Позвонить на городской номер
      share: false
      
    - name: Мобильный телефон
      icon: phone
      username: 8(928)021-52-23
      url: tel:89280215223
      desc: Позвонить
      share: false
      
    - name: Единый номер лесной службы
      icon: phone-square
      username: 8(800)100-94-00
      url: tel:88001009400
      desc: Позвонить на единый номер (звонок из РФ бесплатный)
      share: false
    

    

# Комментарии Disqus
# disqus_shortname: bencentra

# Идентификатор Google Analytics
ga_tracking_id: "UA-86507530-1"